name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.6, 2.7]  # Specify the desired Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install mock future
          pip install .

      - name: Run tests
        run: python -m unittest discover -s tests


  test3:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]  # Specify the desired Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .

      - name: Run tests
        run: python -m unittest discover -s tests
