name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test2:
    runs-on: ubuntu-latest
    container: coatldev/six:latest

    strategy:
      matrix:
        python-version: [2.7]  # Specify the desired Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python2 -m pip install mock future
          python2 -m pip install .

      - name: Run tests
        run: python2 -m unittest discover -s tests


  test3:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.6, 3.12]  # Specify the desired Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .

      - name: Run tests
        run: python -m unittest discover -s tests
